[tox]
envlist = py312

[gh-actions]
python =
    3.12: py312

[testenv]
commands = coverage run --source commercetools --parallel -m pytest {posargs}
extras = test

[testenv:coverage-report]
basepython = python3.12
deps = coverage[toml]
skip_install = true
commands =
    coverage combine
    coverage xml
    coverage report

[testenv:format]
basepython = python3.12
deps =
    black==22.6.0
    isort[toml]==5.10.1
skip_install = true
commands =
    isort --check-only src tests
    black --check src/ tests/
